### PR TITLE
Update UIBaseButton.java

### PR DESCRIPTION
**Pull request by sungerk**

### CODE REVIEW

**Comment by drakeet** [comment]
Nothing explain it?

**Comment by sungerk** [comment]
sorry ... I made a mistake,

**Comment by drakeet** [comment]
This is an endless loop... Maybe you mean `this(context, attrs, 0);`?

**Comment by sungerk** [comment]
yes.

**Comment by drakeet** [comment]
OK, but not necessary. Still thank you!

**Pull request closed without merging**
